export enum ERRORS {
  INVALID_CONFIG_PARAMS = 'INVALID_CONFIG_PARAMS',
  REQUEST_5S_TIMEOUT = 'REQUEST_5S_TIMEOUT',
  ETH_SIGENER_NOT_FOUND = 'ETH_SIGENER_NOT_FOUND',
  TO_NOT_FOUND = 'TO_NOT_FOUND',
  SYMBOL_NOT_FOUND = 'SYMBOL_NOT_FOUND',
  TOKEN_NOT_FOUND = 'TOKEN_NOT_FOUND',
  ACCOUNT_NOT_FOUND = 'ACCOUNT_NOT_FOUND',
  AMOUNT_INVALID = 'AMOUNT_INVALID'
}
